name: bluelab
description: BlueLab - Automated homelab system based on Bluefin-DX
base-image: ghcr.io/ublue-os/bluefin-dx
image-version: 41

modules:
  - type: files
    files:
      - source: bin
        destination: /usr/bin
      - source: lib
        destination: /usr/lib  
      - source: share
        destination: /usr/share
        
  - type: systemd
    system:
      enabled:
        - bluelab-first-boot.service
        - bluelab-updater.timer