---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: bluelab
description: BlueLab - Automated homelab system based on Bluefin-DX
base-image: ghcr.io/ublue-os/bluefin-dx
image-version: 41

modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
        
  - type: systemd
    system:
      enabled:
        - bluelab-updater.timer
        
  - type: rpm-ostree
    install:
      - jq
      - yq
      - git
      - tree
      - gettext
      - htop
      - iotop
      - nethogs
      - variety
      - policycoreutils
      - policycoreutils-python-utils
      - policycoreutils-devel

  - type: script
    scripts:
      - setup-bluelab-environment.sh

  - type: signing # this sets up the proper policy & signing files for signed images to work fully