name: bluelab
description: BlueLab - Automated homelab system based on Bluefin-DX
base-image: ghcr.io/ublue-os/bluefin-dx
image-version: 41

modules:
  - type: files
    files:
      - source: ../files/bin
        destination: /usr/bin
      - source: ../files/lib
        destination: /usr/lib  
      - source: ../files/share
        destination: /usr/share
      - source: ../files/config
        destination: /usr/share/bluelab
        
  - type: systemd
    system:
      enabled:
        - bluelab-first-boot.service
        - bluelab-updater.timer
        
  - type: rpm-ostree
    install:
      - jq
      - yq
      - git
      - tree
      - gettext
      - htop
      - iotop
      - nethogs

  - type: script
    scripts:
      - setup-bluelab-environment.sh